### ISSUE TITLE
Filer always uses "Akademisk Kvart" instead of the chosen alternative

### ISSUE THREAD

**Issue by OlofBen** [bjornregnell/kapten-alloc-web#9] opened 2022-12-08 10:46 UTC

**Comment by bjornregnell** [comment] 2022-12-08 12:10
I'm not sure I understand exactly what you mean. Could you give an example of the current data that is wrong and an example of how you would like it to be?

**Comment by OlofBen** [comment] 2022-12-08 14:34
When the user types "15" in the Filer bar, no times get filtered. This is because all times have an "Akademisk Kvart" e.g. 13:15. The problem is that it does not matter if the “Akademisk Kvart” is checked or not, it will always filter on 13:15 not 13:00. 
    This is a sight inconvenience when you search for times starting at 15:15, and in the ideal world it should filter on 13:15 when the “Akademisk Kvart” is checked and 13:00 when it is not.

**Comment by bjornregnell** [comment] 2022-12-08 15:06
Aha. Well, the "Akademisk kvart" checkbox is related to the download-button "Ladda ner" and not to the filter box... So, if I'm right, it affects how the calendar entries will look in the downloaded .ics file. 

As you might have dates that are 15 and 13 I think it is good to have a colon to make the filtering more specific allowing a differentiation between dates and hours, so could be seen as a "feature and not a bug" .

**Comment by bjornregnell** [comment] 2022-12-08 15:08
![image](https://user-images.githubusercontent.com/3601817/206481720-39c0caa3-4c88-4df9-8eb8-8e1f6b309e4c.png)

**Comment by bjornregnell** [comment] 2022-12-08 15:10
So I'm inclined to close this as "won't fix". Do you think it is ok to type the extra charachter `:` after hours to filter regardless of minutes?

**Comment by bjornregnell** [comment] 2022-12-10 17:50
@OlofBen Is it ok for you with the filtering work-around example above?

**Closed** 2023-09-09 15:12 UTC
Labels: wontfix
